export const BOT_CONNECTED = "BOT_CONNECTED";
export type BOT_CONNECTED = typeof BOT_CONNECTED;

export const BOT_RESPONSE = "BOT_RESPONSE";
export type BOT_RESPONSE = typeof BOT_RESPONSE;

export const BOT_INTERRUPTED = "BOT_INTERRUPTED";
export type BOT_INTERRUPTED = typeof BOT_INTERRUPTED;

export const CONVERSATION_START = "CONVERSATION_START";
export type CONVERSATION_START = typeof CONVERSATION_START;

export const BOT_RESET = "BOT_RESET";
export type BOT_RESET = typeof BOT_RESET;

export const ACCESS_TOKEN_UPDATE = "ACCESS_TOKEN_UPDATE";
export type ACCESS_TOKEN_UPDATE = typeof ACCESS_TOKEN_UPDATE;